[package]
name = "appstream"
description = "Application metadata library"
version = "1.0.4"
subversion = "1"
authors = ["Matthias Klumpp"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "../_scripts/install-meson.sh"

[dependencies]
glibc = ">=2.42.0"
glib = ">=2.84.0"
libxml2 = ">=2.13.0"
libyaml = ">=0.2.5"
libxmlb = ">=0.3.22"
curl = ">=8.13.0"

[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
