[package]
name = "libksba"
description = "X.509, CMS and OCSP parsing library for GnuPG"
version = "1.6.7"
subversion = "1"
authors = ["The GnuPG Project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
libgpg-error = ">=1.55.0"

[dependencies.build]
pkgconf = ">=2.5.0"
