[package]
name = "libvorbis"
description = "Vorbis audio codec library"
version = "1.3.7"
subversion = "1"
authors = ["Xiph.Org Foundation"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "./install.sh"

[dependencies]
glibc = ">=2.42.0"
libogg = ">=1.3.6"

[dependencies.build]
pkgconf = ">=2.5.0"
