[package]
name = "papers"
description = "GNOME papers"
version = "48.4.0"
subversion = "1"
authors = ["The GNOME Project"]
packagers = ["ItzYanick"]
[source]
script = "../_scripts/fetch.sh"
[prepare]
script = "../_scripts/prepare.sh"
[build]
script = "../_scripts/build-meson.sh"
[install]
script = "../_scripts/install-meson.sh"
[dependencies]
+glibc = ">=0.0.0"
glib = ">=0.0.0"
gtk4 = ">=0.0.0"
libadwaita = ">=0.0.0"
gdk-pixbuf = ">=0.0.0"
cairo = ">=0.0.0"
zlib = ">=0.0.0"
exempi = ">=0.0.0"
poppler = ">=0.0.0"
nautilus = ">=0.0.0"
rust = ">=0.0.0"
[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
gettext = ">=0.26.0"
