[package]
name = "libXinerama"
description = "Xinerama extension library"
version = "1.1.5"
subversion = "1"
authors = ["The X.Org Foundation"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
libX11 = "*"
libXext = "*"
xorgproto = "*"

[dependencies.build]
