[package]
name = "bash"
description = "GNU Bourne Again Shell"
version = "5.3.0"
subversion = "2"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
ncurses = ">=6.5.0"

[dependencies.build]
