[package]
name = "mpfr"
description = "Multiple-precision floating-point library"
version = "4.2.2"
subversion = "2"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
gmp = ">=6.3.0"

[dependencies.build]
