[package]
name = "bubblewrap"
description = "Unprivileged sandboxing tool, the program flatpak execs to build a sandbox"
version = "0.11.0"
subversion = "1"
authors = ["Alexander Larsson, Colin Walters and contributors"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "../_scripts/install-meson.sh"

[dependencies]
glibc = ">=2.42.0"
libcap = ">=2.76.0"

[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
