[package]
name = "python-pycparser"
description = "C parser in pure Python"
version = "2.22.0"
subversion = "1"
authors = ["Eli Bendersky"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[install]
script = "install.sh"

[dependencies]
python = ">=3.13.0"

[dependencies.build]
