[package]
name = "glib-introspection"
description = "Introspection data for GLib, GObject, GModule and GIO"
version = "2.84.1"
subversion = "1"
authors = ["The GNOME Project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[build]
script = "build.sh"

[install]
script = "install.sh"

[dependencies]
glib = ">=2.84.0"

[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
gobject-introspection = ">=1.84.0"
