[package]
name = "cargo-c"
description = "Build and install C-ABI artefacts from Rust crates"
version = "0.10.24"
subversion = "1"
authors = ["Luca Barbato"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "./build.sh"

[install]
script = "./install.sh"

[dependencies]
glibc = ">=2.42.0"
gcc = ">=15.2.0"

[dependencies.build]
pkgconf = ">=2.5.0"
