[package]
name = "wayland-protocols"
description = "Wayland protocol extension definitions"
version = "1.41.0"
subversion = "1"
authors = ["The Wayland project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "../_scripts/install-meson.sh"

[dependencies]

[dependencies.build]
meson = ">=1.8.2"
wayland = ">=1.23.1"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
