[package]
name = "pkgconf"
description = "Compiler and linker flag database"
version = "2.5.1"
subversion = "1"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
