[package]
name = "dbus"
description = "Message bus system"
version = "1.16.2"
subversion = "1"
authors = ["The D-Bus project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "../_scripts/install-meson.sh"

[dependencies]
glibc = ">=2.42.0"
expat = ">=2.7.1"

[dependencies.build]
