[package]
name = "python-jinja2"
description = "Templating engine for Python"
version = "3.1.6"
subversion = "1"
authors = ["Pallets"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[install]
script = "install.sh"

[dependencies]
python = ">=3.13.0"
python-markupsafe = ">=3.0.2"

[dependencies.build]
