[package]
name = "libevdev"
description = "Wrapper library for evdev input devices"
version = "1.13.4"
subversion = "1"
authors = ["freedesktop.org"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
pkgconf = ">=2.5.0"
