[package]
name = "libjpeg-turbo"
description = "JPEG image codec"
version = "3.1.0"
subversion = "1"
authors = ["The libjpeg-turbo Project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-cmake.sh"

[install]
script = "../_scripts/install-cmake.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
cmake = ">=4.4.0"
ninja = ">=1.13.0"
