[package]
name = "hwdata"
description = "Hardware identification databases"
version = "0.394.0"
subversion = "1"
authors = ["Red Hat"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "build.sh"

[install]
script = "install.sh"

[dependencies]

[dependencies.build]
