[package]
name = "patch"
description = "GNU patch"
version = "2.8.0"
subversion = "3"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
attr = ">=2.5.2"

[dependencies.build]
