[package]
name = "colord-gtk"
description = "GTK integration library for colord"
version = "0.3.1"
subversion = "1"
authors = ["Richard Hughes"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"
[prepare]
script = "../_scripts/prepare.sh"
[build]
script = "../_scripts/build-meson.sh"
[install]
script = "../_scripts/install-meson.sh"

[dependencies]
glibc = ">=2.42.0"
glib = ">=2.84.0"
gtk4 = ">=4.18.0"
colord = ">=1.4.8"

[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
gobject-introspection = ">=1.84.0"
glib-introspection = ">=2.84.1"
