[package]
name = "libxcvt"
description = "VESA Coordinated Video Timing modeline generator"
version = "0.1.3"
subversion = "1"
authors = ["The X.Org Foundation"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "install.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
meson = ">=1.8.2"
ninja = ">=1.13.0"
