[package]
name = "util-linux"
description = "System utilities: blkid, mount, uuid and the rest"
version = "2.41.1"
subversion = "1"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"
zlib = ">=1.3.1"
ncurses = ">=6.5.0"

[dependencies.build]
