[package]
name = "shared-mime-info"
description = "The freedesktop.org shared MIME database"
version = "2.4.0"
subversion = "1"
authors = ["freedesktop.org"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "../_scripts/install-meson.sh"

[dependencies]
glibc = ">=2.42.0"
glib = ">=2.84.0"
libxml2 = ">=2.13.0"

[dependencies.build]
