[package]
name = "gnome-system-monitor"
description = "GNOME gnome-system-monitor"
version = "48.1.0"
subversion = "1"
authors = ["The GNOME Project"]
packagers = ["ItzYanick"]
[source]
script = "../_scripts/fetch.sh"
[prepare]
script = "../_scripts/prepare.sh"
[build]
script = "../_scripts/build-meson.sh"
[install]
script = "../_scripts/install-meson.sh"
[dependencies]
glibc = ">=0.0.0"
glib = ">=0.0.0"
glibmm = ">=0.0.0"
gtk4 = ">=0.0.0"
gtkmm = ">=0.0.0"
libgtop = ">=0.0.0"
libadwaita = ">=0.0.0"
librsvg = ">=0.0.0"
libxml2 = ">=0.0.0"
catch2 = ">=0.0.0"
[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
gettext = ">=0.26.0"
