[package]
name = "diffutils"
description = "GNU diff, cmp, sdiff and diff3"
version = "3.12.0"
subversion = "2"
authors = ["upstream"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
