[package]
name = "alsa-lib"
description = "Advanced Linux Sound Architecture userspace library"
version = "1.2.14"
subversion = "1"
authors = ["The ALSA project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "install.sh"

[dependencies]
glibc = ">=2.42.0"

[dependencies.build]
