[package]
name = "gnome-menus"
description = "Implementation of the freedesktop menu specification"
version = "3.36.0"
subversion = "1"
authors = ["The GNOME Project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "./install.sh"

[dependencies]
glibc = ">=2.42.0"
glib = ">=2.84.0"

[dependencies.build]
pkgconf = ">=2.5.0"
gobject-introspection = ">=1.84.0"
glib-introspection = ">=2.84.1"
gettext = ">=0.26.0"
