[package]
name = "xorg-util-macros"
description = "Autotools macros shared by the X.Org packages"
version = "1.20.2"
subversion = "1"
authors = ["The X.Org Foundation"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build.sh"

[install]
script = "../_scripts/install.sh"

[dependencies]

[dependencies.build]
