#!/usr/bin/env python3
"""Regenerate tools/program-index.tsv from the locally built packages.

    make program-index

The index maps a program name to the package that ships it, so that
check-recipes.sh can tell that adwaita-icon-theme's find_program call for
gtk4-update-icon-cache means "declare gtk4".

WHY IT IS COMMITTED RATHER THAN COMPUTED

It was computed, from out/pkgs, and that made the check LOCAL-ONLY: CI runs
check-recipes.sh in the select job on a fresh checkout, where out/pkgs does not
exist. The index came out empty, the rule silently checked nothing, and it was
fast for the worst possible reason. A check that is silent in the one place it
most needs to run is worse than a slow one.

So the map is generated here and committed. It is derived from what packages
ACTUALLY SHIP -- never hand-edited -- and check-recipes.sh reports entries it
can see are missing whenever real packages are present, so it cannot rot
unnoticed on a machine that has built anything.

WHY PYTHON, FOR A JOB THAT IS OBVIOUSLY SHELL

This runs on the HOST, and the host here is macOS. The first version was shell
and hit the BSD-versus-GNU trap twice in five minutes: `\\|` alternation in a
basic regular expression is a GNU extension, so BSD sed matched nothing and
reported no error, and the script cheerfully announced "0 entries" as though
that were a result. packages/README.md documents that exact trap. Recipe
scripts may use GNU freely -- they run in the container -- but anything under
tools/ runs wherever the developer is, and Python is the same language on both.
"""

import pathlib
import re
import sys
import tarfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "out" / "pkgs"
INDEX = ROOT / "tools" / "program-index.tsv"

ARCHIVE = re.compile(r"^(?P<name>.+)-\d[^-]*-\d+\.(?:any|aarch64|x86_64)\.tape\.tar\.gz$")
PROGRAM = re.compile(r"^install/usr/(?:bin|sbin|libexec)/([^/]+)$")


def scan() -> dict[str, str]:
    found: dict[str, str] = {}
    for archive in sorted(OUT.glob("*.tape.tar.gz")):
        m = ARCHIVE.match(archive.name)
        if not m:
            continue
        owner = m.group("name")
        # out/pkgs is a build output directory, not a manifest: it keeps
        # whatever has ever been built here, including packages whose recipe
        # lives on another branch.
        if not (ROOT / "pkgs" / owner / "TAPEBUILD.toml").exists():
            continue
        try:
            tf = tarfile.open(archive)
        except (OSError, tarfile.TarError):
            continue
        with tf:
            for member in tf:
                if not (member.isfile() or member.issym()):
                    continue
                hit = PROGRAM.match(member.name)
                if hit:
                    found[hit.group(1)] = owner
    return found


def main() -> int:
    if not OUT.is_dir():
        print(f"no {OUT}; build packages first", file=sys.stderr)
        return 1
    found = scan()
    if not found:
        print(f"no programs found in {OUT}; refusing to write an empty index",
              file=sys.stderr)
        return 1
    lines = ["# GENERATED by tools/gen-program-index.py -- do not edit.",
             "# program\tpackage"]
    lines += [f"{p}\t{o}" for p, o in sorted(found.items())]
    INDEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {INDEX} ({len(found)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
