#!/usr/bin/env bash
# Generate the routine package recipes.
#
# Most of the 29 packages are the same recipe with a different name: fetch,
# configure, make, make install. Writing them by hand would be 100+ files of
# near-identical TOML that drift apart the moment anyone edits one of them.
#
# Only the boring ones are generated. glibc, gcc, ncurses, bash and anything
# else with real quirks is hand-written and left alone -- this script refuses to
# overwrite a recipe that already exists.
#
# Versions come from pkgs/versions.env, so a version bump is one file.

set -euo pipefail

DISTRO=$(cd "$(dirname "$0")/.." && pwd)
PKGS=$DISTRO/pkgs
VERSIONS=$PKGS/versions.env

[ -f "$VERSIONS" ] || { echo "no versions.env -- run tools/pin-versions.sh" >&2; exit 1; }
# shellcheck disable=SC1090
. "$VERSIONS"

# name|description|configure args|runtime deps (space separated)
#
# Runtime dependencies are what the package needs to *run*, which for this set
# is almost always just glibc. Constraints are deliberately loose: tape resolves
# "already visited" by name alone, so in a diamond the first constraint reached
# wins and a tight pin somewhere else would decide the version for everyone.
RECIPES=$(cat <<'EOF'
m4|GNU macro processor||glibc
bison|GNU parser generator||glibc m4
flex|Fast lexical analyser generator||glibc m4
make|GNU make||glibc
gawk|GNU awk||glibc
sed|GNU stream editor||glibc
grep|GNU grep||glibc
findutils|GNU find, xargs and locate|--localstatedir=/var/lib/locate|glibc
diffutils|GNU diff, cmp, sdiff and diff3||glibc
tar|GNU tar archiver||glibc
gzip|GNU compression utility||glibc
patch|GNU patch||glibc
texinfo|GNU documentation system||glibc ncurses
pkgconf|Compiler and linker flag database||glibc
zlib|Compression library||glibc
gmp|GNU multiple precision arithmetic library||glibc
mpfr|Multiple-precision floating-point library||glibc gmp
mpc|Complex number arithmetic library||glibc gmp mpfr
file|File type identification utility|--disable-libseccomp|glibc zlib
xz|XZ compression utilities|--disable-static|glibc
bash|GNU Bourne Again Shell|--without-bash-malloc --with-installed-readline=no|glibc ncurses
ncurses|Terminal handling library|--with-shared --without-normal --without-debug --without-ada --enable-widec --enable-pc-files --with-cxx-shared --with-manpage-format=normal --disable-stripping|glibc
binutils|GNU binary utilities|--enable-gold --enable-ld=default --enable-plugins --enable-64-bit-bfd --enable-new-dtags --enable-default-hash-style=gnu --with-system-zlib --disable-werror --enable-gprofng=no|glibc zlib
EOF
)

# semver3 <version> -- tape skips any package whose version does not parse as
# semver, and it does so silently: the package indexes fine and simply never
# resolves. Padding to three components up front avoids that trap.
semver3() {
	local v=${1%%-*} dots
	# Counted with parameter expansion rather than `wc -c`, which pads its
	# output with spaces on BSD -- the padded value matched no case arm, so
	# every two-component version silently passed through unpadded.
	dots=${v//[^.]/}
	case "${#dots}" in
		0) printf '%s.0.0' "$v" ;;
		1) printf '%s.0' "$v" ;;
		*) printf '%s' "$v" ;;
	esac
}

created=0 skipped=0
while IFS='|' read -r name desc cfgargs deps; do
	[ -n "$name" ] || continue
	dir=$PKGS/$name
	if [ -d "$dir" ]; then
		echo "  skip $name (already exists)"
		skipped=$((skipped + 1))
		continue
	fi

	var=$(echo "$name" | tr '[:lower:]-' '[:upper:]_')
	eval "version=\${${var}_VERSION:-}"
	if [ -z "$version" ]; then
		echo "  !! $name: not in versions.env" >&2
		continue
	fi

	mkdir -p "$dir"

	{
		echo "[package]"
		echo "name = \"$name\""
		echo "description = \"$desc\""
		echo "version = \"$(semver3 "$version")\""
		echo "subversion = \"1\""
		echo "authors = [\"upstream\"]"
		echo "packagers = [\"ItzYanick\"]"
		echo
		echo "[source]"
		echo 'script = "../_scripts/fetch.sh"'
		echo
		echo "[prepare]"
		echo 'script = "../_scripts/prepare.sh"'
		echo
		echo "[build]"
		echo 'script = "../_scripts/build.sh"'
		echo
		echo "[install]"
		echo 'script = "../_scripts/install.sh"'
		echo
		echo "[dependencies]"
		for d in $deps; do
			dvar=$(echo "$d" | tr '[:lower:]-' '[:upper:]_')
			eval "dver=\${${dvar}_VERSION:-}"
			if [ -n "$dver" ]; then
				echo "$d = \">=$(semver3 "$dver")\""
			else
				# glibc and friends that are hand-written recipes still have a
				# version in versions.env; anything else is a genuine mistake.
				echo "$d = \"*\""
			fi
		done
		echo
		echo "[dependencies.build]"
	} >"$dir/TAPEBUILD.toml"

	{
		echo "# $name -- generated by tools/gen-recipes.sh, safe to edit."
		echo "# Source pins come from ../versions.env so a bump is one file."
		echo
		echo "SRC_URL=\$${var}_URL"
		echo "SRC_SHA256=\$${var}_SHA256"
		echo "SRC_DIR=\$${var}_SRCDIR"
		echo
		echo "CONFIGURE_ARGS=\"--disable-nls${cfgargs:+ $cfgargs}\""
	} >"$dir/pkg.env"

	echo "  ok   $name $version"
	created=$((created + 1))
done <<<"$RECIPES"

echo "==> $created created, $skipped left alone"
