[package]
name = "gnome-desktop"
description = "Shared library for GNOME desktop components"
version = "44.3.0"
subversion = "2"
authors = ["The GNOME Project"]
packagers = ["ItzYanick"]

[source]
script = "../_scripts/fetch.sh"

[prepare]
script = "../_scripts/prepare.sh"

[build]
script = "../_scripts/build-meson.sh"

[install]
script = "./install.sh"

[dependencies]
glibc = ">=2.42.0"
glib = ">=2.84.0"
gtk4 = ">=4.18.0"
gtk3 = ">=3.24.0"
gsettings-desktop-schemas = ">=48.0.0"
iso-codes = ">=4.18.0"
libseccomp = ">=2.6.0"
libxml2 = ">=2.13.0"
xkeyboard-config = ">=2.44.0"
eudev = ">=3.2.14"
elogind = ">=255.17.0"

[dependencies.build]
meson = ">=1.8.0"
ninja = ">=1.13.0"
pkgconf = ">=2.5.0"
gobject-introspection = ">=1.84.0"
glib-introspection = ">=2.84.1"
itstool = ">=2.0.7"
gettext = ">=0.26.0"
